services:
  web_app:
    build: ./web_app
    ports:
      - "5002:5002"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/genghis-pond
    command: ["./wait-for-it.sh", "mongodb:27017", "--", "python", "run.py"]

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
