services:
  web_app:
    build: ./web_app
    ports:
      - "5002:5002"
    depends_on:
      - mongodb
    env_file:
      - .env

    command: ["./wait-for-it.sh", "mongodb:27017", "--", "gunicorn", "-c", "gunicorn_config.py", "wsgi:application"]

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
