name: Genghis Pond CI/CD

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        python: ["3.11"]
    steps:
      - name: Clean up Unnecessary Files
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf /usr/local/lib/android
          docker system prune -af

      - name: Checkout Repo to Actions Runner
        uses: actions/checkout@v4

      - name: Manually create .env file
        run: |
          echo "FLASK_ENV=production" >> .env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
          echo "MONGO_URI=mongodb://mongodb:27017/genghis-pond" >> .env

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Setup Containers with Docker Compose
        run: |
          docker compose up -d --build

      - name: Wait for services to be ready
        run: sleep 10

      - name: Install pipenv
        run: pip install pipenv

      - name: Test Web App
        run: |
          pipenv install --dev --skip-lock
          pipenv run python -m pytest

  push_to_docker_hub:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/genghis-pond:latest ./web_app

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/genghis-pond:latest

  deploy:
    needs: push_to_docker_hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Deploy to Droplet using SSH
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
            docker pull ${{ secrets.DOCKER_USERNAME }}/genghis-pond:latest

            docker network create genghis-network || true

            docker stop web_app || true
            docker rm web_app || true
            docker stop mongodb || true
            docker rm mongodb || true

            docker run -d --name mongodb --network genghis-network -p 27017:27017 mongo

            docker run -d --name web_app \
              --network genghis-network \
              -p 5002:5002 \
              -e FLASK_ENV=production \
              -e SECRET_KEY=${{ secrets.SECRET_KEY }} \
              -e MONGO_URI=mongodb://mongodb:27017/genghis-pond \
              ${{ secrets.DOCKER_USERNAME }}/genghis-pond:latest

            sudo systemctl restart nginx
