name: Genghis Pond CI/CD

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.11"]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies and run tests
        run: |
          pipenv install --dev --skip-lock
          pipenv run pytest

  push_to_docker_hub:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/genghis-pond:latest ./web_app
          docker push ${{ secrets.DOCKER_USERNAME }}/genghis-pond:latest

  deploy:
    needs: push_to_docker_hub
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Droplet
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          envs: SECRET_KEY,DOCKER_USERNAME,DOCKER_PASSWORD
          script: |
            docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
            cd 5-final-genghis-pond
            docker-compose pull
            docker-compose down
            docker-compose up -d
