name: Genghis Pond CI/CD

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.11"]
    steps:
      - name: Checkout Repo to Actions Runner
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install pipenv
        run: pip install pipenv

      - name: Set Pipenv Python
        run: pipenv --python $(which python)

      - name: Test Web App
        run: |
          pipenv install --dev --skip-lock
          pipenv run python -m pytest

  push_to_docker_hub:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/genghis-pond:latest ./web_app

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/genghis-pond:latest

  deploy:
    needs: push_to_docker_hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Deploy to Droplet using SSH
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          envs: SECRET_KEY,DOCKER_USERNAME,DOCKER_PASSWORD
          script: |
            echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

            docker pull ${{ secrets.DOCKER_USERNAME }}/genghis-pond:latest

            docker stop web_app || true
            docker rm web_app || true

            docker run -d --name web_app \
              --restart unless-stopped \
              -p 5000:5000 \
              -e FLASK_ENV=production \
              -e SECRET_KEY=${SECRET_KEY} \
              -e MONGO_URI=mongodb://mongodb:27017/genghis-pond \
              ${{ secrets.DOCKER_USERNAME }}/genghis-pond:latest
