name: Genghis Pond CI/CD
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.11"]
    steps:
      - name: Create .env file
        uses: SpicyPizza/create-envfile@v2.0
        with:
          file_name: .env
          directory: .
          fail_on_empty: false
          envs: |
            FLASK_ENV=production
            SECRET_KEY=${{ secrets.SECRET_KEY }}
            MONGO_URI=mongodb://mongodb:27017/genghis-pond

      - name: Checkout Repo to Actions Runner
        uses: actions/checkout@v4
      - name: Install Python 
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Setup Containers with Docker Compose
        run: |
          docker-compose up --build
      - name: Wait for services to be ready
        run: sleep 10
      - name: Install pipenv
        run: pip install pipenv
      - name: Test Web App
        working-directory: web_app
        run: |
          pipenv install pytest
          pipenv --venv
          pipenv install
          pipenv run python -m pytest
  push_to_docker_hub:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/genghis-pond:latest ./web_app
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/genghis-pond:latest

  deploy:
    runs-on: ubuntu-latest
    needs: push_to_docker_hub

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Deploy to Droplet using SSH
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
            docker pull ${{ secrets.DOCKER_USERNAME }}/genghis-pond:latest
            docker stop genghis-pond || true
            docker rm genghis-pond || true
            docker run -d --name genghis-pond -p 5002:5002 --env-file /root/.env ${{ secrets.DOCKER_USERNAME }}/genghis-pond:latest
      