name: Genghis Pond CI/CD

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.11"]
    steps:
      - name: Checkout Repo to Actions Runner
        uses: actions/checkout@v4

      - name: Manually create .env file
        run: |
          echo "FLASK_ENV=production" >> .env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
          echo "MONGO_URI=mongodb://mongodb:27017/genghis-pond" >> .env

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Setup Containers with Docker Compose
        run: |
          docker compose build --pull --no-cache web_app
          docker compose up -d

      - name: Wait for services to be ready
        run: sleep 10

      - name: Install pipenv
        run: pip install pipenv

      - name: Set Pipenv Python
        run: pipenv --python $(which python)

      - name: Test Web App
        run: |
          pipenv install --dev --skip-lock
          pipenv run python -m pytest

  push_to_docker_hub:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/genghis-pond:latest ./web_app

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/genghis-pond:latest

  deploy:
    needs: push_to_docker_hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Deploy to Droplet using SSH
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          envs: SECRET_KEY,DOCKER_USERNAME,DOCKER_PASSWORD
          script: |
            rm -rf /root/app/
            git clone https://github.com/software-students-spring2025/5-final-genghis-pond.git /root/app/
            cd /root/app/ || exit 1
            echo "FLASK_ENV=production" > .env
            echo "SECRET_KEY=${SECRET_KEY}" >> .env
            echo "MONGO_URI=mongodb://mongodb:27017/genghis-pond" >> .env
            echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
            docker compose down --volumes --remove-orphans || true
            docker compose build --pull --no-cache web_app
            docker compose up -d
          

