deploy:
  needs: push_to_docker_hub
  runs-on: ubuntu-latest
  steps:
    - name: Checkout the repo
      uses: actions/checkout@v4

    - name: Deploy to Droplet using SSH
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        envs: SECRET_KEY,DOCKER_USERNAME,DOCKER_PASSWORD
        script: |
          rm -rf /root/app/
          git clone https://github.com/software-students-spring2025/5-final-genghis-pond.git /root/app/
          cd /root/app/
          echo "FLASK_ENV=production" > .env
          echo "SECRET_KEY=${SECRET_KEY}" >> .env
          echo "MONGO_URI=mongodb://mongodb:27017/genghis-pond" >> .env
          echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
          docker compose down --volumes --remove-orphans || true
          docker compose build --pull --no-cache web_app
          docker compose up -d
