name: Genghis Pond CI/CD
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.11"]
    steps:
      - name: Checkout Repo to Actions Runner
        uses: actions/checkout@v4
      - name: Install Python 
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Setup Containers with Docker Compose
        run: |
          docker compose up -d --build
      - name: Wait for services to be ready
        run: sleep 10
      - name: Install pipenv
        run: pip install pipenv
      - name: Test Web App
        working-directory: web_app
        run: |
          pipenv install pytest
          pipenv --venv
          pipenv install
          pipenv run python -m pytest
  push_to_docker_hub:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/genghis-pond:latest ./web_app
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/genghis-pond:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          source: "."
          target: "${{ env.PROJECT_DIR }}"
        